CREATE DATABASE IF NOT EXISTS NotesDB;

USE NotesDB;

CREATE TABLE IF NOT EXISTS Users (
    UserID INT NOT NULL AUTO_INCREMENT,
    UserName VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL,
    PRIMARY KEY (UserID)
);

CREATE TABLE IF NOT EXISTS UserNotes (
    UserID INT NOT NULL,
    NoteID INT NOT NULL AUTO_INCREMENT,
    NoteTitle TEXT NOT NULL,
    NoteText TEXT,
    PRIMARY KEY (NoteID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);
